version: "3.6"

services:
  meow:
    build: .
    command: "meow-service"
    depends_on:
      - "kafka"
    ports:
      - "8000:3000"
  pusher:
    build: .
    command: "pusher-service"
    depends_on:
      - "kafka"
    ports:
      - "8001:3000"
  storage:
    build: .
    command: "storage-service"
    depends_on:
      - "kafka"
      - "postgres"
    ports:
      - "8002:3000"
  postgres:
    build: "./postgres"
    restart: "always"
    environment:
      POSTGRES_USER: "meower"
      POSTGRES_DB: "meower"
      POSTGRES_PASSWORD: "123456"
  kafka:
    image: "spotify/kafka"
    restart: "always"
